# Generated by Django 4.2.26 on 2025-11-09 22:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotelrebates', '0003_bank'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Brand',
            new_name='HotelCorporation',
        ),
    ]
