# Generated by Django 4.2.26 on 2025-11-15 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotelrebates', '0004_rename_brand_hotelcorporation'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotelcorporation',
            name='terms_and_conditions',
            field=models.TextField(blank=True, null=True),
        ),
    ]
