# Generated by Django 4.2.26 on 2025-11-15 05:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotelrebates', '0005_hotelcorporation_terms_and_conditions'),
    ]

    operations = [
        migrations.CreateModel(
            name='TravelAgency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='currency',
            name='cpp',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
        migrations.AlterField(
            model_name='hotelcorporation',
            name='terms_and_conditions',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='CreditCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_name', models.CharField(max_length=100)),
                ('general_hotel_points_per_dollar', models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True)),
                ('hotel_corporation_points_per_dollar', models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True)),
                ('travel_portal_points_per_dollar', models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True)),
                ('everywhere_points_per_dollar', models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True)),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotelrebates.bank')),
                ('earn_currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotelrebates.currency')),
                ('hotel_corporation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hotelrebates.hotelcorporation')),
                ('travel_portal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hotelrebates.travelagency')),
            ],
        ),
    ]
