# Generated by Django 4.2.26 on 2025-11-15 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotelrebates', '0006_travelagency_alter_currency_cpp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditcard',
            name='everywhere_points_per_dollar',
            field=models.DecimalField(decimal_places=1, default=1, max_digits=3),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='creditcard',
            name='general_hotel_points_per_dollar',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True),
        ),
        migrations.AlterField(
            model_name='creditcard',
            name='hotel_corporation_points_per_dollar',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True),
        ),
        migrations.AlterField(
            model_name='creditcard',
            name='travel_portal_points_per_dollar',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True),
        ),
    ]
