# Generated by Django 4.2.26 on 2025-11-15 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotelrebates', '0007_alter_creditcard_everywhere_points_per_dollar_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditcard',
            name='hotel_corporation_points_per_stay',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
