# Generated by Django 4.2.26 on 2025-11-16 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotelrebates', '0008_creditcard_hotel_corporation_points_per_stay'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditcard',
            name='ota_points_per_dollar',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True),
        ),
    ]
