# Generated by Django 4.2.26 on 2025-11-16 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotelrebates', '0010_alter_creditcard_everywhere_points_per_dollar_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditcard',
            name='everywhere_points_per_dollar',
            field=models.DecimalField(decimal_places=3, max_digits=5),
        ),
        migrations.AlterField(
            model_name='creditcard',
            name='general_hotel_points_per_dollar',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='creditcard',
            name='hotel_corporation_points_per_dollar',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='creditcard',
            name='ota_points_per_dollar',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='creditcard',
            name='travel_portal_points_per_dollar',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=5, null=True),
        ),
    ]
