# Generated by Django 4.2.26 on 2025-11-16 19:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotelrebates', '0011_alter_creditcard_everywhere_points_per_dollar_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HotelEliteStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_name', models.CharField(max_length=100)),
                ('points_earning_bonus_percent', models.IntegerField()),
                ('corporation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotelrebates.hotelcorporation')),
            ],
        ),
    ]
