# Generated by Django 4.2.26 on 2025-11-23 20:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotelrebates', '0012_hotelelitestatus'),
    ]

    operations = [
        migrations.CreateModel(
            name='CashbackPortal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PortalOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cashback_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('terms_and_conditions', models.TextField(blank=True, null=True)),
                ('last_seen', models.DateField()),
                ('hotel_corporation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotelrebates.hotelcorporation')),
                ('portal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotelrebates.cashbackportal')),
            ],
        ),
    ]
