# Generated by Django 4.2.26 on 2025-11-23 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotelrebates', '0013_cashbackportal_portaloffer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portaloffer',
            name='last_seen',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
