# Generated by Django 4.2.26 on 2025-11-25 05:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotelrebates', '0014_alter_portaloffer_last_seen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portaloffer',
            name='hotel_corporation',
        ),
        migrations.AddField(
            model_name='portaloffer',
            name='travel_agency',
            field=models.ForeignKey(default=7, on_delete=django.db.models.deletion.CASCADE, to='hotelrebates.travelagency'),
            preserve_default=False,
        ),
    ]
