# Generated by Django 4.2.26 on 2025-11-25 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotelrebates', '0015_remove_portaloffer_hotel_corporation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='portaloffer',
            name='test',
            field=models.TextField(blank=True, null=True),
        ),
    ]
