# Generated by Django 4.2.26 on 2025-11-25 05:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotelrebates', '0016_portaloffer_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portaloffer',
            name='test',
        ),
    ]
